require("custom.core")
require("custom.lazy")

vim.cmd("highlight Normal guibg=NONE")
vim.cmd("highlight NormalNC guibg=NONE")
vim.cmd("highlight IndentLineCurrent guibg=NONE guifg=#aaaaaa")
vim.cmd("highlight WinSeparator guifg=#aaaaaa")
vim.cmd("highlight NormalFloat guibg=NONE")
vim.cmd("highlight FloatBorder guibg=NONE")
vim.cmd("highlight FloatTitle guibg=NONE")
vim.cmd("highlight FloatFooter guibg=NONE")
vim.cmd("highlight Pmenu guibg=NONE")
vim.cmd("highlight PmenuSel guibg=NONE")
vim.cmd("highlight CursorLine guibg=NONE")
vim.cmd("highlight WinBar guibg=NONE")
vim.cmd("highlight WinBarNC guibg=NONE")
vim.cmd("highlight StatusLine guibg=NONE")
vim.cmd("highlight StatusLineNC guibg=NONE")
vim.cmd("highlight TabLine guibg=NONE")
vim.cmd("highlight TabLineFill guibg=NONE")
vim.cmd("highlight PmenuSbar guibg=NONE")
vim.cmd("highlight MsgSeparator guibg=NONE")
vim.cmd("highlight CursorLineFold guibg=NONE")
vim.cmd("highlight CursorLineSign guibg=NONE")
vim.cmd("highlight FoldColumn guibg=NONE")
vim.cmd("highlight SignColumn guibg=NONE")
vim.cmd("highlight EndOfBuffer guibg=NONE guifg=#aaaaaa")

require('transparent').clear_prefix('BufferLine')
require('transparent').clear_prefix('notify')
require('transparent').clear_prefix('nvim-tree')
require('transparent').clear_prefix('mason')
require('transparent').clear_prefix('lazy')
require('transparent').clear_prefix('telescope')
require('transparent').clear_prefix('trouble')

vim.cmd("set laststatus=3")
vim.cmd("set fillchars+=eob:│")
